CREATE TABLE ITEM(
	ES_ID 		SMALLINT,
	I_NO 		SMALLINT,
	NAME 		VARCHAR(60) NOT NULL,
	S_PRICE 	SMALLINT 	NOT NULL,
	E_PRICE 	SMALLINT 	NOT NULL,
	QUANTITY 	SMALLINT 	DEFAULT(1),
	RETFLG 		BIT 		NOT NULL,
	PRICE 		SMALLINT 	NOT NULL,
	PRINTFLG 	BIT 		DEFAULT(0),
	PRIMARY KEY(ES_ID,I_NO)
)
